export type TeamSeed = {
  code: string
  name: string
  groupCode: string
  stickers: string[]
}

export type SpecialSeed = {
  code: string
  name: string
}

export const WC2026_SPECIALS: SpecialSeed[] = [
  { code: "00", name: "Logo Panini" },
  { code: "FWC1", name: "Emblema Oficial (parte superior)" },
  { code: "FWC2", name: "Emblema Oficial (parte inferior)" },
  { code: "FWC3", name: "Mascotas Oficiales (Mape, Zayu, Clutch)" },
  { code: "FWC4", name: "Lema Oficial (We Are 26)" },
  { code: "FWC5", name: "Balón Oficial (Trionda)" },
  { code: "FWC6", name: "Emblema País Anfitrión (CAN-MEX-USA)" },
  { code: "FWC7", name: "Emblema País Anfitrión (CAN-MEX-USA)" },
  { code: "FWC8", name: "Emblema País Anfitrión (CAN-MEX-USA)" },
  { code: "FWC9", name: "Italia 1934 (Italia)" },
  { code: "FWC10", name: "Brasil 1950 (Uruguay)" },
  { code: "FWC11", name: "Suiza 1954 (Alemania)" },
  { code: "FWC12", name: "Chile 1962 (Brasil)" },
  { code: "FWC13", name: "Alemania 1974 (Alemania)" },
  { code: "FWC14", name: "México 1986 (Argentina)" },
  { code: "FWC15", name: "EE.UU. 1994 (Brasil, penaltis)" },
  { code: "FWC16", name: "Corea/Japón 2002 (Brasil)" },
  { code: "FWC17", name: "Alemania 2006 (Italia, penaltis)" },
  { code: "FWC18", name: "Brasil 2014 (Alemania)" },
  { code: "FWC19", name: "Catar 2022 (Argentina, penaltis)" },
]

export const WC2026_TEAMS: TeamSeed[] = [
  {
    code: "MEX",
    name: "México",
    groupCode: "A",
    stickers: [
      "Logo",
      "Luis Malagón",
      "Johan Vásquez",
      "Jorge Sánchez",
      "César Montes",
      "Jesús Gallardo",
      "Israel Reyes",
      "Diego Lainez",
      "Carlos Rodríguez",
      "Edson Álvarez",
      "Orbelín Pineda",
      "Marcel Ruiz",
      "Line-Up",
      "Érick Sánchez",
      "Hirving Lozano",
      "Santiago Giménez",
      "Raúl Jiménez",
      "Alexis Vega",
      "Roberto Alvarado",
      "César Huerta",
    ],
  },
  {
    code: "RSA",
    name: "Sudáfrica",
    groupCode: "A",
    stickers: [
      "Logo",
      "Ronwen Williams",
      "Sipho Chaine",
      "Aubrey Modiba",
      "Samukele Kabini",
      "Mbekezeli Mbokazi",
      "Khulumani Ndamane",
      "Siyabonga Ngezana",
      "Khuliso Mudau",
      "Nkosinathi Sibisi",
      "Teboho Mokoena",
      "Thalente Mbatha",
      "Line-Up",
      "Bathusi Aubaas",
      "Yaya Sithole",
      "Sipho Mbule",
      "Lyle Foster",
      "Iqraam Rayners",
      "Mohau Nkota",
      "Oswin Appollis",
    ],
  },
  {
    code: "KOR",
    name: "Corea del Sur",
    groupCode: "A",
    stickers: [
      "Logo",
      "Hyeonwoo Jo",
      "Seunggyu Kim",
      "Minjae Kim",
      "Yumin Cho",
      "Youngwoo Seol",
      "Hanbeom Lee",
      "Taeseok Lee",
      "Myungjae Lee",
      "Jaesung Lee",
      "Inbeom Hwang",
      "Kangin Lee",
      "Line-Up",
      "Seungho Paik",
      "Jens Castrop",
      "Donggyeong Lee",
      "Guesung Cho",
      "Heungmin Son",
      "Heechan Hwang",
      "Hyeongyu Oh",
    ],
  },
  {
    code: "CZE",
    name: "Chequia",
    groupCode: "A",
    stickers: [
      "Logo",
      "Matěj Kovář",
      "Jindřich Staněk",
      "Ladislav Krejčí",
      "Vladimír Coufal",
      "Jaroslav Zelený",
      "Tomáš Holeš",
      "David Zima",
      "Michal Sadílek",
      "Lukáš Provod",
      "Lukáš Červ",
      "Tomáš Souček",
      "Line-Up",
      "Pavel Šulc",
      "Matěj Vydra",
      "Vasil Kušej",
      "Tomáš Chorý",
      "Václav Černý",
      "Adam Hložek",
      "Patrik Schick",
    ],
  },
  {
    code: "CAN",
    name: "Canadá",
    groupCode: "B",
    stickers: [
      "Logo",
      "Dayne St. Clair",
      "Alphonso Davies",
      "Alistair Johnston",
      "Samuel Adekugbe",
      "Richie Laryea",
      "Derek Cornelius",
      "Moïse Bombito",
      "Kamal Miller",
      "Stephen Eustáquio",
      "Ismaël Koné",
      "Jonathan Osorio",
      "Line-Up",
      "Jacob Shaffelburg",
      "Mathieu Choinière",
      "Niko Sigur",
      "Tajon Buchanan",
      "Liam Millar",
      "Cyle Larin",
      "Jonathan David",
    ],
  },
  {
    code: "BIH",
    name: "Bosnia y Herzegovina",
    groupCode: "B",
    stickers: [
      "Logo",
      "Nikola Vasilj",
      "Amar Dedić",
      "Sead Kolašinac",
      "Tarik Muharemović",
      "Nihad Mujakić",
      "Nikola Katić",
      "Amir Hadžiahmetović",
      "Benjamin Tahirović",
      "Armin Gigović",
      "Ivan Šunjić",
      "Ivan Bašić",
      "Team",
      "Dženis Burnić",
      "Esmir Bajraktarević",
      "Amar Memić",
      "Ermedin Demirović",
      "Edin Džeko",
      "Samed Baždar",
      "Haris Tabaković",
    ],
  },
  {
    code: "QAT",
    name: "Catar",
    groupCode: "B",
    stickers: [
      "Logo",
      "Meshaal Barsham",
      "Sultan Albrake",
      "Lucas Mendes",
      "Homam Ahmed",
      "Boualem Khoukhi",
      "Pedro Miguel",
      "Tarek Salman",
      "Mohammed Mannai",
      "Karim Boudiaf",
      "Assim Madibo",
      "Hamed Fatehi",
      "Line-Up",
      "Mohammed Waad",
      "Abdulaziz Hatem",
      "Hassan Al-Haydos",
      "Edmílson Junior",
      "Akram Hassan Afif",
      "Ahmed Al-Ganehi",
      "Almoez Ali",
    ],
  },
  {
    code: "SUI",
    name: "Suiza",
    groupCode: "B",
    stickers: [
      "Logo",
      "Gregor Kobel",
      "Yvon Mvogo",
      "Manuel Akanji",
      "Ricardo Rodríguez",
      "Nico Elvedi",
      "Aurèle Amenda",
      "Silvan Widmer",
      "Granit Xhaka",
      "Denis Zakaria",
      "Remo Freuler",
      "Fabian Rieder",
      "Line-Up",
      "Ardon Jashari",
      "Johan Manzambi",
      "Michel Aebischer",
      "Breel Embolo",
      "Rubén Vargas",
      "Dan Ndoye",
      "Zeki Amdouni",
    ],
  },
  {
    code: "BRA",
    name: "Brasil",
    groupCode: "C",
    stickers: [
      "Logo",
      "Alisson",
      "Bento",
      "Marquinhos",
      "Éder Militão",
      "Gabriel Magalhães",
      "Danilo",
      "Wesley",
      "Lucas Paquetá",
      "Casemiro",
      "Bruno Guimarães",
      "Luiz Henrique",
      "Line-Up",
      "Vinícius Júnior",
      "Rodrygo",
      "João Pedro",
      "Matheus Cunha",
      "Gabriel Martinelli",
      "Raphinha",
      "Estêvão",
    ],
  },
  {
    code: "MAR",
    name: "Marruecos",
    groupCode: "C",
    stickers: [
      "Logo",
      "Yassine Bounou",
      "Munir El Kajoui",
      "Achraf Hakimi",
      "Noussair Mazraoui",
      "Nayef Aguerd",
      "Roman Saïss",
      "Jawad El Yamiq",
      "Adam Masina",
      "Sofyan Amrabat",
      "Azzedine Ounahi",
      "Eliesse Ben Seghir",
      "Line-Up",
      "Bilal El Khannouss",
      "Ismael Saibari",
      "Youssef En-Nesyri",
      "Abde Ezzalzouli",
      "Soufiane Rahimi",
      "Brahim Díaz",
      "Ayoub El Kaabi",
    ],
  },
  {
    code: "HAI",
    name: "Haití",
    groupCode: "C",
    stickers: [
      "Logo",
      "Johny Placide",
      "Carlens Arcus",
      "Martin Expérience",
      "Jean-Kévin Duverne",
      "Ricardo Adé",
      "Duke Lacroix",
      "Garven Metusala",
      "Hannes Delcroix",
      "Leverton Pierre",
      "Danley Jean Jacques",
      "Jean-Ricner Bellegarde",
      "Line-Up",
      "Christopher Attys",
      "Derrick Etienne Jr.",
      "Josué Casimir",
      "Ruben Providence",
      "Duckens Nazon",
      "Louicius Deedson",
      "Frantzdy Pierrot",
    ],
  },
  {
    code: "SCO",
    name: "Escocia",
    groupCode: "C",
    stickers: [
      "Logo",
      "Angus Gunn",
      "Jack Hendry",
      "Kieran Tierney",
      "Aaron Hickey",
      "Andrew Robertson",
      "Scott McKenna",
      "John Souttar",
      "Anthony Ralston",
      "Grant Hanley",
      "Scott McTominay",
      "Billy Gilmour",
      "Line-Up",
      "Lewis Ferguson",
      "Ryan Christie",
      "Kenny McLean",
      "John McGinn",
      "Lyndon Dykes",
      "Ché Adams",
      "Ben Gannon-Doak",
    ],
  },
  {
    code: "USA",
    name: "Estados Unidos",
    groupCode: "D",
    stickers: [
      "Logo",
      "Matt Freese",
      "Chris Richards",
      "Tim Ream",
      "Mark McKenzie",
      "Alex Freeman",
      "Antonee Robinson",
      "Tyler Adams",
      "Tanner Tessmann",
      "Weston McKennie",
      "Christian Roldan",
      "Timothy Weah",
      "Line-Up",
      "Diego Luna",
      "Malik Tillman",
      "Christian Pulisic",
      "Brenden Aaronson",
      "Ricardo Pepi",
      "Haji Wright",
      "Folarin Balogun",
    ],
  },
  {
    code: "PAR",
    name: "Paraguay",
    groupCode: "D",
    stickers: [
      "Logo",
      "Roberto Fernández",
      "Orlando Gill",
      "Gustavo Gómez",
      "Fabián Balbuena",
      "Juan José Cáceres",
      "Omar Alderete",
      "Júnior Alonso",
      "Mathías Villasanti",
      "Diego Gómez",
      "Damián Bobadilla",
      "Andrés Cubas",
      "Line-Up",
      "Matías Galarza Fonda",
      "Julio Enciso",
      "Alejandro Romero Gamarra",
      "Miguel Almirón",
      "Ramón Sosa",
      "Ángel Romero",
      "Antonio Sanabria",
    ],
  },
  {
    code: "AUS",
    name: "Australia",
    groupCode: "D",
    stickers: [
      "Logo",
      "Mathew Ryan",
      "Joe Gauci",
      "Harry Souttar",
      "Alessandro Circati",
      "Jordan Bos",
      "Aziz Behich",
      "Cameron Burgess",
      "Lewis Miller",
      "Milos Degenek",
      "Jackson Irvine",
      "Riley McGree",
      "Line-Up",
      "Aiden O'Neill",
      "Connor Metcalfe",
      "Patrick Yazbek",
      "Craig Goodwin",
      "Kusini Yengi",
      "Nestory Irankunda",
      "Mohamed Touré",
    ],
  },
  {
    code: "TUR",
    name: "Turquía",
    groupCode: "D",
    stickers: [
      "Logo",
      "Uğurcan Çakır",
      "Mert Müldür",
      "Zeki Çelik",
      "Abdülkerim Bardakci",
      "Çağlar Söyüncü",
      "Merih Demiral",
      "Ferdi Kadioğlu",
      "Kaan Ayhan",
      "Ismail Yüksek",
      "Hakan Çalhanoğlu",
      "Orkun Kökçü",
      "Line-Up",
      "Arda Güler",
      "Irfan Can Kahveci",
      "Yunus Akgün",
      "Can Uzun",
      "Barış Alper Yılmaz",
      "Kerem Aktürkoğlu",
      "Kenan Yıldız",
    ],
  },
  {
    code: "GER",
    name: "Alemania",
    groupCode: "E",
    stickers: [
      "Logo",
      "Marc-André ter Stegen",
      "Jonathan Tah",
      "David Raum",
      "Nico Schlotterbeck",
      "Antonio Rüdiger",
      "Waldemar Anton",
      "Ridle Baku",
      "Maximilian Mittelstädt",
      "Joshua Kimmich",
      "Florian Wirtz",
      "Felix Nmecha",
      "Line-Up",
      "Leon Goretzka",
      "Jamal Musiala",
      "Serge Gnabry",
      "Kai Havertz",
      "Leroy Sané",
      "Karim Adeyemi",
      "Nick Woltemade",
    ],
  },
  {
    code: "CUW",
    name: "Curazao",
    groupCode: "E",
    stickers: [
      "Logo",
      "Eloy Room",
      "Armando Obispo",
      "Sherel Floranus",
      "Juriën Gaari",
      "Joshua Brenet",
      "Roshon Van Eijma",
      "Shurandy Sambo",
      "Livano Comenencia",
      "Godfried Roemeratoe",
      "Juninho Bacuna",
      "Leandro Bacuna",
      "Line-Up",
      "Tahith Chong",
      "Kenji Gorré",
      "Jearl Margaritha",
      "Jürgen Locadia",
      "Jeremy Antonisse",
      "Gervane Kastaneer",
      "Sontje Hansen",
    ],
  },
  {
    code: "CIV",
    name: "Costa de Marfil",
    groupCode: "E",
    stickers: [
      "Logo",
      "Yahia Fofana",
      "Ghislain Konan",
      "Wilfried Singo",
      "Odilon Kossounou",
      "Evan Ndicka",
      "Willy Boly",
      "Emmanuel Agbadou",
      "Ousmane Diomande",
      "Franck Kessié",
      "Seko Fofana",
      "Ibrahim Sangaré",
      "Line-Up",
      "Jean-Philippe Gbamin",
      "Amad Diallo",
      "Sébastien Haller",
      "Simon Adingra",
      "Yan Diomande",
      "Evann Guessand",
      "Oumar Diakité",
    ],
  },
  {
    code: "ECU",
    name: "Ecuador",
    groupCode: "E",
    stickers: [
      "Logo",
      "Hernán Galíndez",
      "Gonzalo Valle",
      "Piero Hincapié",
      "Pervis Estupiñán",
      "William Pacho",
      "Ángelo Preciado",
      "Joel Ordóñez",
      "Moisés Caicedo",
      "Alan Franco",
      "Kendry Páez",
      "Pedro Vite",
      "Line-Up",
      "John Yeboah",
      "Leonardo Campana",
      "Gonzalo Plata",
      "Nilson Angulo",
      "Alan Minda",
      "Kevin Rodríguez",
      "Enner Valencia",
    ],
  },
  {
    code: "NED",
    name: "Países Bajos",
    groupCode: "F",
    stickers: [
      "Logo",
      "Bart Verbruggen",
      "Virgil van Dijk",
      "Micky van de Ven",
      "Jurriën Timber",
      "Denzel Dumfries",
      "Nathan Aké",
      "Jeremie Frimpong",
      "Jan Paul van Hecke",
      "Tijjani Reijnders",
      "Ryan Gravenberch",
      "Teun Koopmeiners",
      "Line-Up",
      "Frenkie de Jong",
      "Xavi Simons",
      "Justin Kluivert",
      "Memphis Depay",
      "Donyell Malen",
      "Wout Weghorst",
      "Cody Gakpo",
    ],
  },
  {
    code: "JPN",
    name: "Japón",
    groupCode: "F",
    stickers: [
      "Logo",
      "Zion Suzuki",
      "Henry Hiroki Mochizuki",
      "Ayumu Seko",
      "Junnosuke Suzuki",
      "Shogo Taniguchi",
      "Tsuyoshi Watanabe",
      "Kaishu Sano",
      "Yuki Soma",
      "Ao Tanaka",
      "Daichi Kamada",
      "Takefusa Kubo",
      "Line-Up",
      "Ritsu Doan",
      "Keito Nakamura",
      "Takumi Minamino",
      "Shuto Machino",
      "Junya Ito",
      "Koki Ogawa",
      "Ayase Ueda",
    ],
  },
  {
    code: "SWE",
    name: "Suecia",
    groupCode: "F",
    stickers: [
      "Logo",
      "Victor Johansson",
      "Isak Hien",
      "Gabriel Gudmundsson",
      "Emil Holm",
      "Victor Nilsson Lindelöf",
      "Gustaf Lagerbielke",
      "Lucas Bergvall",
      "Hugo Larsson",
      "Jesper Karlström",
      "Yasin Ayari",
      "Mattias Svanberg",
      "Line-Up",
      "Daniel Svensson",
      "Ken Sema",
      "Roony Bardghji",
      "Dejan Kulusevski",
      "Anthony Elanga",
      "Alexander Isak",
      "Viktor Gyökeres",
    ],
  },
  {
    code: "TUN",
    name: "Túnez",
    groupCode: "F",
    stickers: [
      "Logo",
      "Bechir Ben Saïd",
      "Aymen Dahmen",
      "Yan Valery",
      "Montassar Talbi",
      "Yassine Meriah",
      "Ali Abdi",
      "Dylan Bronn",
      "Ellyes Skhiri",
      "Aïssa Laïdouni",
      "Ferjani Sassi",
      "Mohamed Ali Ben Romdhane",
      "Line-Up",
      "Hannibal Mejbri",
      "Elias Achouri",
      "Elias Saad",
      "Hazem Mastouri",
      "Ismaël Gharbi",
      "Sayfallah Ltaief",
      "Naïm Sliti",
    ],
  },
  {
    code: "BEL",
    name: "Bélgica",
    groupCode: "G",
    stickers: [
      "Logo",
      "Thibaut Courtois",
      "Arthur Theate",
      "Timothy Castagne",
      "Zeno Debast",
      "Brandon Mechele",
      "Maxim De Cuyper",
      "Thomas Meunier",
      "Youri Tielemans",
      "Amadou Onana",
      "Nicolas Raskin",
      "Alexis Saelemaekers",
      "Line-Up",
      "Hans Vanaken",
      "Kevin De Bruyne",
      "Jérémy Doku",
      "Charles De Ketelaere",
      "Leandro Trossard",
      "Loïs Openda",
      "Romelu Lukaku",
    ],
  },
  {
    code: "EGY",
    name: "Egipto",
    groupCode: "G",
    stickers: [
      "Logo",
      "Mohamed El Shenawy",
      "Mohamed Hany",
      "Mohamed Hamdy",
      "Yasser Ibrahim",
      "Khaled Sobhi",
      "Ramy Rabia",
      "Hossam Abdelmaguid",
      "Ahmed Fatouh",
      "Marwan Attia",
      "Zizo",
      "Hamdy Fathy",
      "Line-Up",
      "Mohanad Lasheen",
      "Emam Ashour",
      "Osama Faisal",
      "Mohamed Salah",
      "Mostafa Mohamed",
      "Trezeguet",
      "Omar Marmoush",
    ],
  },
  {
    code: "IRN",
    name: "Irán",
    groupCode: "G",
    stickers: [
      "Logo",
      "Alireza Beiranvand",
      "Morteza Pouraliganji",
      "Ehsan Hajsafi",
      "Milad Mohammadi",
      "Shojae Khalilzadeh",
      "Ramin Rezaeian",
      "Hossein Kanaani",
      "Sadegh Moharrami",
      "Saleh Hardani",
      "Saeid Ezatolahi",
      "Saman Ghoddos",
      "Line-Up",
      "Omid Noorafkan",
      "Roozbeh Cheshmi",
      "Mohammad Mohebi",
      "Sardar Azmoun",
      "Mehdi Taremi",
      "Alireza Jahanbakhsh",
      "Ali Gholizadeh",
    ],
  },
  {
    code: "NZL",
    name: "Nueva Zelanda",
    groupCode: "G",
    stickers: [
      "Logo",
      "Max Crocombe",
      "Alex Paulsen",
      "Michael Boxall",
      "Liberato Cacace",
      "Tim Payne",
      "Tyler Bindon",
      "Francis de Vries",
      "Finn Surman",
      "Joe Bell",
      "Sarpreet Singh",
      "Ryan Thomas",
      "Line-Up",
      "Matthew Garbett",
      "Marko Stamenić",
      "Ben Old",
      "Chris Wood",
      "Elijah Just",
      "Callum McCowatt",
      "Kosta Barbarouses",
    ],
  },
  {
    code: "ESP",
    name: "España",
    groupCode: "H",
    stickers: [
      "Logo",
      "Unai Simón",
      "Robin Le Normand",
      "Aymeric Laporte",
      "Dean Huijsen",
      "Pedro Porro",
      "Dani Carvajal",
      "Marc Cucurella",
      "Martín Zubimendi",
      "Rodri",
      "Pedri",
      "Fabián Ruiz",
      "Line-Up",
      "Mikel Merino",
      "Lamine Yamal",
      "Dani Olmo",
      "Nico Williams",
      "Ferran Torres",
      "Álvaro Morata",
      "Mikel Oyarzabal",
    ],
  },
  {
    code: "CPV",
    name: "Cabo Verde",
    groupCode: "H",
    stickers: [
      "Logo",
      "Vozinha",
      "Logan Costa",
      "Pico",
      "Diney",
      "Steven Moreira",
      "Wagner Pina",
      "João Paulo",
      "Yannick Semedo",
      "Kevin Pina",
      "Patrick Andrade",
      "Jamiro Monteiro",
      "Line-Up",
      "Deroy Duarte",
      "Garry Rodrigues",
      "Jovane Cabral",
      "Ryan Mendes",
      "Dailon Livramento",
      "Willy Semedo",
      "Bebé",
    ],
  },
  {
    code: "KSA",
    name: "Arabia Saudí",
    groupCode: "H",
    stickers: [
      "Logo",
      "Nawaf Alaqidi",
      "Abdulrahman Al-Sanbi",
      "Saud Abdulhamid",
      "Nawaf Buwashl",
      "Jehad Thikri",
      "Moteb Alharbi",
      "Hassan Altambakti",
      "Musab Aljuwayr",
      "Ziyad Aljohani",
      "Abdullah Alkhaibari",
      "Nasser Aldawsari",
      "Line-Up",
      "Saleh Abu Alshamat",
      "Marwan Alsahafi",
      "Salem Aldawsari",
      "Abdulrahman Alobud",
      "Feras Albrikan",
      "Saleh Alshehri",
      "Abdullah Alhamdan",
    ],
  },
  {
    code: "URU",
    name: "Uruguay",
    groupCode: "H",
    stickers: [
      "Logo",
      "Sergio Rochet",
      "Santiago Mele",
      "Ronald Araújo",
      "José María Giménez",
      "Sebastián Cáceres",
      "Mathías Olivera",
      "Guillermo Varela",
      "Nahitan Nández",
      "Federico Valverde",
      "Giorgian De Arrascaeta",
      "Rodrigo Bentancur",
      "Line-Up",
      "Manuel Ugarte",
      "Nicolás de la Cruz",
      "Maxi Araújo",
      "Darwin Núñez",
      "Federico Viñas",
      "Rodrigo Aguirre",
      "Facundo Pellistri",
    ],
  },
  {
    code: "FRA",
    name: "Francia",
    groupCode: "I",
    stickers: [
      "Logo",
      "Mike Maignan",
      "Theo Hernández",
      "William Saliba",
      "Jules Koundé",
      "Ibrahima Konaté",
      "Dayot Upamecano",
      "Lucas Digne",
      "Aurélien Tchouaméni",
      "Eduardo Camavinga",
      "Manu Koné",
      "Adrien Rabiot",
      "Line-Up",
      "Michael Olise",
      "Ousmane Dembélé",
      "Bradley Barcola",
      "Désiré Doué",
      "Kingsley Coman",
      "Hugo Ekitiké",
      "Kylian Mbappé",
    ],
  },
  {
    code: "SEN",
    name: "Senegal",
    groupCode: "I",
    stickers: [
      "Logo",
      "Édouard Mendy",
      "Yehvann Diouf",
      "Moussa Niakhaté",
      "Abdoulaye Seck",
      "Ismail Jakobs",
      "El Hadji Malick Diouf",
      "Kalidou Koulibaly",
      "Idrissa Gana Gueye",
      "Pape Matar Sarr",
      "Pape Gueye",
      "Habib Diarra",
      "Line-Up",
      "Lamine Camara",
      "Sadio Mané",
      "Ismaïla Sarr",
      "Boulaye Dia",
      "Iliman Ndiaye",
      "Nicolas Jackson",
      "Krépin Diatta",
    ],
  },
  {
    code: "IRQ",
    name: "Irak",
    groupCode: "I",
    stickers: [
      "Logo",
      "Jalal Hassan",
      "Rebin Sulaka",
      "Hussein Ali",
      "Akam Hashem",
      "Merchas Doski",
      "Zaid Tahseen",
      "Manaf Younis",
      "Zidane Iqbal",
      "Amir Al-Ammari",
      "Ibrahim Bavesh",
      "Ali Jasim",
      "Line-Up",
      "Youssef Amyn",
      "Aimar Sher",
      "Marko Farji",
      "Osama Rashid",
      "Ali Al-Hamadi",
      "Aymen Hussein",
      "Mohanad Ali",
    ],
  },
  {
    code: "NOR",
    name: "Noruega",
    groupCode: "I",
    stickers: [
      "Logo",
      "Ørjan Nyland",
      "Julian Ryerson",
      "Leo Østigård",
      "Kristoffer Vassbakk Ajer",
      "Marcus Holmgren Pedersen",
      "David Møller Wolfe",
      "Torbjørn Heggem",
      "Morten Thorsby",
      "Martin Ødegaard",
      "Sander Berge",
      "Andreas Schjelderup",
      "Line-Up",
      "Patrick Berg",
      "Erling Haaland",
      "Alexander Sørloth",
      "Aron Dønnum",
      "Jørgen Strand Larsen",
      "Antonio Nusa",
      "Oscar Bobb",
    ],
  },
  {
    code: "ARG",
    name: "Argentina",
    groupCode: "J",
    stickers: [
      "Logo",
      "Emiliano Martínez",
      "Nahuel Molina",
      "Cristian Romero",
      "Nicolás Otamendi",
      "Nicolás Tagliafico",
      "Leonardo Balerdi",
      "Enzo Fernández",
      "Alexis Mac Allister",
      "Rodrigo De Paul",
      "Exequiel Palacios",
      "Leandro Paredes",
      "Line-Up",
      "Nico Paz",
      "Franco Mastantuono",
      "Nico González",
      "Lionel Messi",
      "Lautaro Martínez",
      "Julián Alvarez",
      "Giuliano Simeone",
    ],
  },
  {
    code: "ALG",
    name: "Argelia",
    groupCode: "J",
    stickers: [
      "Logo",
      "Alexis Guendouz",
      "Ramy Bensebaini",
      "Youcef Atal",
      "Rayan Aït-Nouri",
      "Mohamed Amine Tougai",
      "Aïssa Mandi",
      "Ismaël Bennacer",
      "Houssem Aouar",
      "Hicham Boudaoui",
      "Ramiz Zerrouki",
      "Nabil Bentaleb",
      "Line-Up",
      "Farès Chaïbi",
      "Riyad Mahrez",
      "Saïd Benrahma",
      "Anis Hadj Moussa",
      "Amine Gouiri",
      "Baghdad Bounedjah",
      "Mohamed Amoura",
    ],
  },
  {
    code: "AUT",
    name: "Austria",
    groupCode: "J",
    stickers: [
      "Logo",
      "Alexander Schlager",
      "Patrick Pentz",
      "David Alaba",
      "Kevin Danso",
      "Philipp Lienhart",
      "Stefan Posch",
      "Philipp Mwene",
      "Alexander Prass",
      "Xaver Schlager",
      "Marcel Sabitzer",
      "Konrad Laimer",
      "Line-Up",
      "Florian Grillitsch",
      "Nicolas Seiwald",
      "Romano Schmid",
      "Patrick Wimmer",
      "Christoph Baumgartner",
      "Michael Gregoritsch",
      "Marko Arnautović",
    ],
  },
  {
    code: "JOR",
    name: "Jordania",
    groupCode: "J",
    stickers: [
      "Logo",
      "Yazeed Abulaila",
      "Ihsan Haddad",
      "Mohammad Abu Hashish",
      "Yazan Al-Arab",
      "Abdallah Nasib",
      "Saleem Obaid",
      "Mohammad Abualnadi",
      "Ibrahim Saadeh",
      "Nizar Al-Rashdan",
      "Noor Al-Rawabdeh",
      "Mohannad Abu Taha",
      "Line-Up",
      "Amer Jamous",
      "Musa Al-Taamari",
      "Yazan Al-Naimat",
      "Mahmoud Al-Mardi",
      "Ali Olwan",
      "Mohammad Abu Zrayq",
      "Ibrahim Sabra",
    ],
  },
  {
    code: "POR",
    name: "Portugal",
    groupCode: "K",
    stickers: [
      "Logo",
      "Diogo Costa",
      "José Sá",
      "Rúben Dias",
      "João Cancelo",
      "Diogo Dalot",
      "Nuno Mendes",
      "Gonçalo Inácio",
      "Bernardo Silva",
      "Bruno Fernandes",
      "Rúben Neves",
      "Vitinha",
      "Line-Up",
      "João Neves",
      "Cristiano Ronaldo",
      "Francisco Trincão",
      "João Félix",
      "Gonçalo Ramos",
      "Pedro Neto",
      "Rafael Leão",
    ],
  },
  {
    code: "COD",
    name: "RD del Congo",
    groupCode: "K",
    stickers: [
      "Logo",
      "Lionel Mpasi",
      "Aaron Wan-Bissaka",
      "Axel Tuanzebe",
      "Arthur Masuaku",
      "Chancel Mbemba",
      "Joris Kayembe",
      "Charles Pickel",
      "Ngal'ayel Mukau",
      "Edo Kayembe",
      "Samuel Moutoussamy",
      "Noah Sadiki",
      "Line-Up",
      "Théo Bongonda",
      "Meschak Elia",
      "Yoane Wissa",
      "Brian Cipenga",
      "Fiston Mayele",
      "Cédric Bakambu",
      "Nathanaël Mbuku",
    ],
  },
  {
    code: "UZB",
    name: "Uzbekistán",
    groupCode: "K",
    stickers: [
      "Logo",
      "Utkir Yusupov",
      "Farrukh Sayfiev",
      "Sherzod Nasrullaev",
      "Umar Eshmurodov",
      "Husniddin Aliqulov",
      "Rustam Ashurmatov",
      "Khojiakbar Alijonov",
      "Abdukodir Khusanov",
      "Odiljon Hamrobekov",
      "Otabek Shukurov",
      "Jamshid Iskanderov",
      "Line-Up",
      "Azizbek Turgunboev",
      "Khojimat Erkinov",
      "Eldor Shomurodov",
      "Oston Urunov",
      "Jaloliddin Masharipov",
      "Igor Sergeev",
      "Abbosbek Fayzullaev",
    ],
  },
  {
    code: "COL",
    name: "Colombia",
    groupCode: "K",
    stickers: [
      "Logo",
      "Camilo Vargas",
      "David Ospina",
      "Dávinson Sánchez",
      "Yerry Mina",
      "Daniel Muñoz",
      "Johan Mojica",
      "Jhon Lucumí",
      "Santiago Arias",
      "Jefferson Lerma",
      "Kevin Castaño",
      "Richard Ríos",
      "Team",
      "James Rodríguez",
      "Juan Fernando Quintero",
      "Jorge Carrascal",
      "Jhon Arias",
      "Jhon Córdoba",
      "Luis Suárez",
      "Luis Díaz",
    ],
  },
  {
    code: "ENG",
    name: "Inglaterra",
    groupCode: "L",
    stickers: [
      "Logo",
      "Jordan Pickford",
      "John Stones",
      "Marc Guéhi",
      "Ezri Konsa",
      "Trent Alexander-Arnold",
      "Reece James",
      "Dan Burn",
      "Jordan Henderson",
      "Declan Rice",
      "Jude Bellingham",
      "Cole Palmer",
      "Line-Up",
      "Morgan Rogers",
      "Anthony Gordon",
      "Phil Foden",
      "Bukayo Saka",
      "Harry Kane",
      "Marcus Rashford",
      "Ollie Watkins",
    ],
  },
  {
    code: "CRO",
    name: "Croacia",
    groupCode: "L",
    stickers: [
      "Logo",
      "Dominik Livaković",
      "Duje Ćaleta-Car",
      "Joško Gvardiol",
      "Josip Stanišić",
      "Luka Vušković",
      "Josip Šutalo",
      "Kristijan Jakić",
      "Luka Modrić",
      "Mateo Kovačić",
      "Martin Baturina",
      "Lovro Majer",
      "Line-Up",
      "Mario Pašalić",
      "Petar Sučić",
      "Ivan Perišić",
      "Marco Pašalić",
      "Ante Budimir",
      "Andrej Kramarić",
      "Franjo Ivanović",
    ],
  },
  {
    code: "GHA",
    name: "Ghana",
    groupCode: "L",
    stickers: [
      "Logo",
      "Lawrence Ati Zigi",
      "Tariq Lamptey",
      "Mohammed Salisu",
      "Alidu Seidu",
      "Alexander Djiku",
      "Gideon Mensah",
      "Caleb Yirenkyi",
      "Abdul Issahaku Fatawu",
      "Thomas Partey",
      "Salis Abdul Samed",
      "Kamaldeen Sulemana",
      "Line-Up",
      "Mohammed Kudus",
      "Iñaki Williams",
      "Jordan Ayew",
      "André Ayew",
      "Joseph Paintsil",
      "Osman Bukari",
      "Antoine Semenyo",
    ],
  },
  {
    code: "PAN",
    name: "Panamá",
    groupCode: "L",
    stickers: [
      "Logo",
      "Orlando Mosquera",
      "Luis Mejía",
      "Fidel Escobar",
      "Andrés Andrade",
      "Michael Amir Murillo",
      "Eric Davis",
      "José Córdoba",
      "César Blackman",
      "Cristian Martínez",
      "Aníbal Godoy",
      "Adalberto Carrasquilla",
      "Line-Up",
      "Édgar Bárcenas",
      "Carlos Harvey",
      "Ismael Díaz",
      "José Fajardo",
      "Cecilio Waterman",
      "José Luis Rodríguez",
      "Alberto Quintero",
    ],
  },
]
